#!/bin/bash

set -e

PATH=/bin:/sbin:/usr/bin:/usr/sbin

case "$1" in
    configure)
          cat <<-END

		========== Important RevPiPyLoad post-installation note ==========

    By default the XML-RPC service listens on localhost only. To access the
    daemon via RevPiCommander from your network, please change the
    bindip in /etc/revpipyload/revpipyload.conf or execute:

                  sudo revpipyload_secure_installation

	END
     ;;
esac

#DEBHELPER#

exit 0
